/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utility_Picosel */

#ifndef _Included_utility_Picosel
#define _Included_utility_Picosel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utility_Picosel
 * Method:    invokePicosel
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_utility_Picosel_invokePicosel
  (JNIEnv *, jclass, jstring, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
